#!/usr/bin/env python3

# Copyright (C) 2024  Martin Michlmayr <tbm@cyrius.com>
# License: GNU General Public License (GPL), version 3 or above
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Download pages from Swahili Wiktionary

FIXME: this needs to be merged with the main download/download
"""

__license__ = "GPL-3.0-or-later"

from pathlib import Path
import re
import time

import click
import pywikibot

import kamusi


def get_text(page):
    """
    Get the text from a Wikimedia page - try again if there's a server error
    """
    try:
        return page.text
    except pywikibot.exceptions.ServerError:
        print("Sleeping before trying again...")
        time.sleep(20)
        return get_text(page)


# FIXME: merge this into kamusi.get_entry()
def get_entry(text, lang, strip=False):
    """
    Get the entry for a specific language from a text
    """
    start = re.search(r"==\s*\{\{(--?\|)?" + lang + r"\s*\}\}\s*==", text)
    if not start:
        return None
    text = text[start.start() :]
    end = re.search(r"\n==[^=]", text)
    if end:
        text = text[: end.start() + 1]
    if strip:
        return text.rstrip()
    return text


@click.command()
@click.option("--lang", type=str, required=True, help="Language code")
@click.option("--out", type=click.Path(), required=True, help="Directory for output")
def download(lang, out):
    """
    Downlodad lemmas and store them in a directory
    """
    out = Path(out)
    Path.mkdir(out, exist_ok=True)
    site = pywikibot.Site("sw", "wiktionary")
    category = pywikibot.Category(site, "Maneno ya " + kamusi.code_to_name(lang, "sw"))
    for page in category.articles():
        print(page.title())
        text = get_entry(get_text(page), lang, strip=True)
        if not text:
            print("Can't get entry for", page.title())
            continue
        outfile = out / Path(page.title().replace("/", "_"))
        with open(outfile, "w", encoding="utf-8") as outfile:
            print(text, file=outfile)


if __name__ == "__main__":
    download()  # pylint: disable=no-value-for-parameter
