lang_map = {
    "af": "Afrikaans",
    "ar": "Arabic",
    "bcl": "Bikol Central",
    "ca": "Catalan",
    "ceb": "Cebuano",
    "de": "German",
    "en": "English",
    "enm": "Middle English",
    "fr": "French",
    "hil": "Hiligaynon",
    "iba": "Iban",
    "id": "Indonesian",
    "ilo": "Ilocano",
    "it": "Italian",
    "lo": "Lao",
    "ms": "Malay",
    "nl": "Dutch",
    "om": "Oromo",
    "pag": "Pangasinan",
    "pam": "Kapampangan",
    "pt": "Portuguese",
    "sh": "Serbo-Croatian",
    "sv": "Swedish",
    "sw": "Swahili",
    "tl": "Tagalog",
    "tpi": "Tok Pisin",
    "ttj": "Tooro",
}
