#!/usr/bin/env python3

# Copyright (C) 2024  Martin Michlmayr <tbm@cyrius.com>
# License: GNU General Public License (GPL), version 3 or above
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Add plural to noun
"""

__license__ = "GPL-3.0-or-later"

import sys

import click
import pywikibot

import kamusi

finals = ["ך", "ם", "ן", "ף", "ץ"]


def add_noun_plural(entry_name, entry, gender, plural):
    """
    Add plural to noun
    """
    if entry_name[-1] in finals:
        print("Page ends in letter that changes - currently unsupported")
        sys.exit(1)
    if "{{yi-subst-" in entry:
        print("Page already has plural info")
        sys.exit(1)
    for line in entry.splitlines(keepends=True):
        if line == "{{subst|yi}}\n":
            line = "{{yi-subst-" + gender + "-" + plural + "}}\n"
        yield line


@click.command()
@click.argument("page")
@click.argument("gender")
@click.argument("plural")
def main(page, gender, plural):
    """
    Add plural to noun
    """
    site = pywikibot.Site("sv", "wiktionary")
    page = pywikibot.Page(site, page)
    lang = "yi"
    old_text = kamusi.get_entry(page.text, lang, site="sv")
    if not old_text:
        print(f"No page {page} for language {lang}")
        sys.exit(1)
    new_text = "".join(add_noun_plural(page.title(), old_text, gender, plural))
    if old_text == new_text:
        print("No change")
        sys.exit(1)
    changelog = kamusi.format_changelog("Add plural to noun", lang, "sv")
    print(kamusi.colour_diff(old_text, new_text))
    edit = input("Store edit (Y/n): ")
    if not edit.upper() == "N":
        page.text = page.text.replace(old_text, new_text)
        page.save(changelog, minor=False)


if __name__ == "__main__":
    main()  # pylint: disable=no-value-for-parameter
