#!/usr/bin/env python3

r"""
Merge multiple hyphenation templates into one

You can find entries that need this change with this query:

    rg "\{\{hyph.*\};? ['\w]"
"""

import re
import sys

import click
import pywikibot

import kamusi


def merge_hyph(entry):
    """
    Merge multiple hyphenation templates into one
    """
    for line in entry.splitlines():
        if "{{hyph" in line:
            line = re.sub(r"\|nocaption=(1|y|yes)", "", line)
            line = re.sub(
                r"\}\};? '*\(?(also|or)\)?'* {{(hyph|hyphenation)\|\w{2,3}\|",
                "||",
                line,
            )
        yield line


@click.command()
@click.argument("page")
@click.option("--lang", default="de", help="Language code")
def main(page, lang):
    """
    Merge multiple hyphenation templates into one
    """
    site = pywikibot.Site("en", "wiktionary")
    page = pywikibot.Page(site, page)
    old_text = kamusi.get_entry(page.text, lang)
    if not old_text:
        print(f"No page {page} for language {lang}")
        sys.exit(1)
    new_text = "\n".join(merge_hyph(old_text))
    if old_text == new_text:
        print("No change")
        sys.exit(1)
    changelog = kamusi.format_changelog(lang, "Merge hyphenation info")
    print(kamusi.colour_diff(old_text, new_text))
    edit = input("Store edit (Y/n): ")
    if not edit.upper() == "N":
        page.text = page.text.replace(old_text, new_text)
        page.save(changelog, minor=False)


if __name__ == "__main__":
    main()  # pylint: disable=no-value-for-parameter
