#!/usr/bin/env python3

# Copyright (C) 2024  Martin Michlmayr <tbm@cyrius.com>
# License: GNU General Public License (GPL), version 3 or above
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Remove empty lines in translation
"""

__license__ = "GPL-3.0-or-later"

import sys

import click
import pywikibot

import kamusi


def remove_empty_line(entry):
    """
    Remove empty lines in translation
    """
    in_trans = False
    for line in entry.splitlines(keepends=True):
        if line.startswith("{{trans-top"):
            in_trans = True
        elif line.startswith("{{checktrans-top"):
            in_trans = True
        elif line.startswith("{{trans-bottom"):
            in_trans = False
        elif in_trans and not line.strip():
            # skip empty line
            continue
        yield line


@click.command()
@click.argument("page")
def main(page):
    """
    Remove empty lines in translation
    """
    site = pywikibot.Site("en", "wiktionary")
    page = pywikibot.Page(site, page)
    lang = "en"
    old_text = kamusi.get_entry(page.text, lang)
    if not old_text:
        print(f"No page {page} for language {lang}")
        sys.exit(1)
    new_text = "".join(remove_empty_line(old_text))
    if old_text == new_text:
        print("No change")
        sys.exit(1)
    changelog = "/* Translations */ Remove empty lines in translation"
    print(kamusi.colour_diff(old_text, new_text))
    print(new_text)
    edit = input("Store edit (Y/n): ")
    if not edit.upper() == "N":
        page.text = page.text.replace(old_text, new_text)
        page.save(changelog, minor=True)


if __name__ == "__main__":
    main()  # pylint: disable=no-value-for-parameter
