#!/usr/bin/env python3

# Copyright (C) 2024  Martin Michlmayr <tbm@cyrius.com>
# License: GNU General Public License (GPL), version 3 or above
# SPDX-License-Identifier: GPL-3.0-or-later

r"""
Fix wrong order of transliteration and noun gender

Search like this:
    rg "^'''.*''' \{\{.\}\} \([a-zA-Z]+"
"""

__license__ = "GPL-3.0-or-later"

import re
import sys

import click
import pywikibot

import kamusi


def fix_translit_order(entry):
    """
    Fix wrong order of transliteration and noun gender
    """
    for line in entry.splitlines(keepends=True):
        if match := re.match(r"('''.*''')\s*(\{\{.\}\})\s*(\(.*\))", line):
            line = match.group(1) + " " + match.group(3) + " " + match.group(2) + "\n"
        yield line


@click.command()
@click.argument("page")
@click.option("--lang", default="yi", help="Language code")
def main(page, lang):
    """
    Fix wrong order of transliteration and noun gender
    """
    site = pywikibot.Site("sv", "wiktionary")
    page = pywikibot.Page(site, page)
    old_text = kamusi.get_entry(page.text, lang, site="sv")
    if not old_text:
        print(f"No page {page} for language {lang}")
        sys.exit(1)
    new_text = "".join(fix_translit_order(old_text))
    if old_text == new_text:
        print("No change")
        sys.exit(1)
    changelog = kamusi.format_changelog("Fix order of transliteration", lang, "sv")
    print(kamusi.colour_diff(old_text, new_text))
    edit = input("Store edit (Y/n): ")
    if not edit.upper() == "N":
        page.text = page.text.replace(old_text, new_text)
        page.save(changelog, minor=False)


if __name__ == "__main__":
    main()  # pylint: disable=no-value-for-parameter
