#!/usr/bin/env python3

# Copyright (C) 2024  Martin Michlmayr <tbm@cyrius.com>
# License: GNU General Public License (GPL), version 3 or above
# SPDX-License-Identifier: GPL-3.0-or-later

r"""
Fix the separation for gender alternatives

Alternatives should be separated by ''eller'' ("or" in Swedish)
and not by a slash.

Search like this:
    rg "^'''.*''' \([a-z]+\) \{\{.\}\}\s*/"
"""

__license__ = "GPL-3.0-or-later"

import re
import sys

import click
import pywikibot

import kamusi


def fix_translit_order(entry):
    """
    Fix wrong order of transliteration and noun gender
    """
    for line in entry.splitlines(keepends=True):
        if line.startswith("'''"):
            line = re.sub(r"\s*/\s*", " ''eller'' ", line)
        yield line


@click.command()
@click.argument("page")
@click.option("--lang", default="yi", help="Language code")
def main(page, lang):
    """
    Fix the separation for gender alternatives.
    """
    site = pywikibot.Site("sv", "wiktionary")
    page = pywikibot.Page(site, page)
    old_text = kamusi.get_entry(page.text, lang, site="sv")
    if not old_text:
        print(f"No page {page} for language {lang}")
        sys.exit(1)
    new_text = "".join(fix_translit_order(old_text))
    if old_text == new_text:
        print("No change")
        sys.exit(1)
    changelog = kamusi.format_changelog(
        "Standardize separation of gender alternatives", lang, "sv"
    )
    print(kamusi.colour_diff(old_text, new_text))
    edit = input("Store edit (Y/n): ")
    if not edit.upper() == "N":
        page.text = page.text.replace(old_text, new_text)
        page.save(changelog, minor=True)


if __name__ == "__main__":
    main()  # pylint: disable=no-value-for-parameter
