#!/usr/bin/env python3

# Copyright (C) 2024  Martin Michlmayr <tbm@cyrius.com>
# License: GNU General Public License (GPL), version 3 or above
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Add missing {{infl}} header.

"""

__license__ = "GPL-3.0-or-later"

import re
import sys

import click
import pywikibot

import kamusi


def get_entry(text, lang, strip=False):
    """
    Get the entry for a specific language from a text
    """
    start = re.search(r"==\s*\{\{(--?\|)?" + lang + r"\s*\}\}\s*==", text)
    if not start:
        return None
    text = text[start.start() :]
    end = re.search(r"\n==[^=]", text)
    if end:
        text = text[: end.start() + 1]
    if strip:
        return text.rstrip()
    return text


WORD_CLASSES = [
    "nomino",
    "kitenzi",
    "kivumishi",
    "kiunganishi",
    "kielezi",
    "kihusishi",
    "kirai",
]


def get_word_class(header):
    """
    Determine the word class based on the header
    """
    # This is a little simplistic but it's better for now until we clean
    # up all the headers.
    for word_class in WORD_CLASSES:
        if word_class in header.lower():
            return word_class
    return None


def add_infl(match):
    """
    Add inflection template based on header
    """
    word_class = get_word_class(match.group(1))
    # Return unchanged if it's not a world class (e.g. "Tafsiri")
    if not word_class:
        return match.group(0)
    infl = "{{infl|sw|" + word_class + "}}\n\n"
    return match.group(1) + infl + match.group(3)


@click.command()
@click.argument("page_name")
@click.option("--lang", default="sw", help="Language code")
def main(page_name, lang):
    """
    Add inflection template
    """
    site = pywikibot.Site("sw", "wiktionary")
    page = pywikibot.Page(site, page_name)
    lang = "sw"
    old_text = get_entry(page.text, lang)
    if not old_text:
        print(f"No page {page} for language {lang}")
        sys.exit(1)
    new_text = old_text
    new_text = re.sub(r"(===.*?===\n)(\n*)(#)", add_infl, new_text)
    if old_text == new_text:
        print("No change")
        sys.exit(1)
    changelog = "/* {{sw}} */ Convert inflection info to template"
    print(kamusi.colour_diff(old_text, new_text))
    print(new_text)
    edit = input("Store edit (Y/n): ")
    if not edit.upper() == "N":
        page.text = page.text.replace(old_text, new_text)
        page.save(changelog, minor=False)


if __name__ == "__main__":
    main()  # pylint: disable=no-value-for-parameter
