#!/usr/bin/env python3

# Copyright (C) 2024  Martin Michlmayr <tbm@cyrius.com>
# License: GNU General Public License (GPL), version 3 or above
# SPDX-License-Identifier: GPL-3.0-or-later

r"""
Fix the position order of inflection info

Find with these calls:
    rg "\{\{infl.*nomino\|wingi"
    rg "\{\{infl.*wingi\|\|[\w\s]+\}\}"
"""

__license__ = "GPL-3.0-or-later"

import re
import sys

import click
import pywikibot

import kamusi


def fix_infl_pos_order(entry):
    """
    Fix mistakes in the position order of elements of the inflection info
    """
    for line in entry.splitlines(keepends=True):
        if line.startswith("{{infl|"):
            # "nomino" must be followed by noun class,
            # the plural ("wingi") is one position after.
            line = line.replace("nomino|wingi", "nomino||wingi")
            # The plural should directly follow "wingi"; if
            # there's one argument only two positions later,
            # that's probably the plural.
            if re.search(r"wingi\s*\|\|[\w\s]+\}\}", line):
                line = line.replace("wingi||", "wingi|")
        yield line


@click.command()
@click.argument("page")
def main(page):
    """
    Fix the position order of inflection info
    """
    site = pywikibot.Site("sw", "wiktionary")
    page = pywikibot.Page(site, page)
    lang = "sw"
    old_text = page.text
    if not old_text:
        print(f"No page {page} for language {lang}")
        sys.exit(1)
    new_text = old_text
    new_text = "".join(fix_infl_pos_order(new_text))
    if old_text == new_text:
        print("No change")
        sys.exit(1)
    changelog = "/* {{sw}} */ Fix position order of inflection info"
    print(kamusi.colour_diff(old_text, new_text))
    print(new_text)
    edit = input("Store edit (Y/n): ")
    if not edit.upper() == "N":
        page.text = page.text.replace(old_text, new_text)
        page.save(changelog, minor=False)


if __name__ == "__main__":
    main()  # pylint: disable=no-value-for-parameter
