#!/usr/bin/env python3

"""
Add category to Wiktionry entry
"""

import sys

import click
import kamusi
import pywikibot
import requests


def check_category(category, lang):
    """
    Check whether a category page exists
    """
    url = "https://en.wiktionary.org/wiki/Category:" + lang + ":" + category
    url = url.replace(" ", "_")
    category_page = requests.head(url, timeout=5)
    if not category_page.ok:
        return False
    return True


@click.command()
@click.argument("page")
@click.argument("category")
@click.option("--lang", default="sw", help="Language code")
def add_category_page(page, category, lang):
    """
    Add category to page
    """

    for cat in category.split("|"):
        if not check_category(cat, lang):
            print(f"Category {cat} doesn't exist for language {lang}")
            sys.exit(1)
    site = pywikibot.Site("en", "wiktionary")
    page = pywikibot.Page(site, page)
    old_text = kamusi.get_entry(page.text, lang)
    if not old_text:
        print(f"No page {page} for language {lang}")
        sys.exit(1)
    new_text = kamusi.add_category(old_text, category, lang)
    if old_text == new_text:
        print("No change")
        sys.exit(1)
    changelog = f"/* {kamusi.lang_map[lang]} */ Add category"
    print(kamusi.colour_diff(old_text, new_text))
    edit = input("Store edit (Y/n): ")
    if not edit.upper() == "N":
        page.text = page.text.replace(old_text, new_text)
        page.save(changelog, minor=False)


if __name__ == "__main__":
    add_category_page()  # pylint: disable=no-value-for-parameter
