#!/usr/bin/env python3

# Copyright (C) 2024  Martin Michlmayr <tbm@cyrius.com>
# License: GNU General Public License (GPL), version 3 or above
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Add Wikipedia link to Wiktionry entry
"""

__license__ = "GPL-3.0-or-later"

import sys

import click
import pywikibot
import requests

import kamusi


def check_wikipedia(page, lang):
    """
    Check whether a Wikipedia page exists
    """
    url = "https://" + lang + ".wikipedia.org/wiki/" + page[0].upper() + page[1:]
    url = url.replace(" ", "_")
    wp = requests.head(url, timeout=5)
    if not wp.ok:
        return False
    return True


@click.command()
@click.argument("page")
@click.argument("wikipedia", required=False)
@click.option("--lang", default="sw", help="Language code")
def add_wikipedia_page(page, wikipedia, lang):
    """
    Add Wikipedia link to page
    """
    if not check_wikipedia(wikipedia or page, lang):
        print("Wikipedia page doesn't exist")
        sys.exit(1)
    site = pywikibot.Site("en", "wiktionary")
    page = pywikibot.Page(site, page)
    old_text = kamusi.get_entry(page.text, lang)
    if not old_text:
        print(f"No page {page} for language {lang}")
        sys.exit(1)
    new_text = kamusi.add_wikipedia(old_text, lang, wikipedia)
    if old_text == new_text:
        print("No change")
        sys.exit(1)
    changelog = kamusi.format_changelog(lang, "Add link to Wikipedia")
    print(kamusi.colour_diff(old_text, new_text))
    edit = input("Store edit (Y/n): ")
    if not edit.upper() == "N":
        page.text = page.text.replace(old_text, new_text)
        page.save(changelog, minor=False)


if __name__ == "__main__":
    add_wikipedia_page()  # pylint: disable=no-value-for-parameter
