#!/usr/bin/env python3

"""
Add thumbnail to Wiktionry entry
"""

import sys

import click
import kamusi
import pywikibot
import requests


def check_commons(page):
    """
    Check whether a Wikimedia Commons page exists
    """
    url = "https://commons.wikimedia.org/wiki/" + page
    url = url.replace(" ", "_")
    commons = requests.head(url, timeout=5)
    if not commons.ok:
        return False
    return True


@click.command()
@click.argument("page")
@click.argument("thumbnail")
@click.option("--lang", default="sw", help="Language code")
def add_thumbnail_page(page, thumbnail, lang):
    """
    Add thumbnail to entry
    """
    thumbnail = thumbnail.replace("Image:", "File:")
    thumbnail = thumbnail.replace("Faili:", "File:")
    if not thumbnail.startswith("File:"):
        thumbnail = "File:" + thumbnail
    if not check_commons(thumbnail):
        print("Commons page doesn't exist")
        sys.exit(1)
    site = pywikibot.Site("en", "wiktionary")
    page = pywikibot.Page(site, page)
    old_text = kamusi.get_entry(page.text, lang)
    if not old_text:
        print(f"No page {page} for language {lang}")
        sys.exit(1)
    new_text = kamusi.add_thumbnail(old_text, thumbnail)
    if old_text == new_text:
        print("No change")
        sys.exit(1)
    changelog = f"/* {kamusi.lang_map[lang]} */ Add thumbnail"
    print(new_text)
    edit = input("Store edit (Y/n): ")
    if not edit.upper() == "N":
        page.text = page.text.replace(old_text, new_text)
        page.save(changelog, minor=False)


if __name__ == "__main__":
    add_thumbnail_page()  # pylint: disable=no-value-for-parameter
