#!/usr/bin/env python3

# Copyright (C) 2024  Martin Michlmayr <tbm@cyrius.com>
# License: GNU General Public License (GPL), version 3 or above
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Add Arabic root to page
"""

__license__ = "GPL-3.0-or-later"

import re
import sys

import click
import pywikibot

import kamusi


@click.command()
@click.argument("page")
@click.argument("root")
@click.option("--lang", default="sw", help="Language code")
def add_arabic_root(page, root, lang):
    """
    Add Arabic root to page
    """
    site = pywikibot.Site("en", "wiktionary")
    page = pywikibot.Page(site, page)
    old_text = kamusi.get_entry(page.text, lang)
    if not old_text:
        print(f"No page {page} for language {lang}")
        sys.exit(1)
    root = "{{root|" + lang + "|ar|" + root + "}}"
    if root in old_text:
        print("Root already listed in entry")
        sys.exit(1)
    if "{{root|" in old_text:
        print("Page lists different root")
        sys.exit(1)
    new_text = old_text
    new_text = re.sub(r"(\|...?\|ar\|[^}]+\}\}\.)\n", r"\1 " + root + "\n", new_text)
    if old_text == new_text:
        print("No change")
        sys.exit(1)
    changelog = kamusi.format_changelog("Add Arabic root", lang)
    print(kamusi.colour_diff(old_text, new_text))
    edit = input("Store edit (Y/n): ")
    if not edit.upper() == "N":
        page.text = page.text.replace(old_text, new_text)
        page.save(changelog, minor=False)


if __name__ == "__main__":
    add_arabic_root()  # pylint: disable=no-value-for-parameter
