#!/usr/bin/env python3

"""
Download pages
"""

import re
from pathlib import Path
import sys

import kamusi
import pywikibot


def download(outdir):
    """
    Downlodad lemmas and store them in a directory
    """
    Path.mkdir(outdir, exist_ok=True)
    site = pywikibot.Site("en", "wiktionary")
    lang = "ttj"
    lemmas = pywikibot.Category(site, kamusi.lang_map[lang] + "_lemmas")
    for page in lemmas.articles():
        print(page.title())
        text = kamusi.get_entry(page.text, lang)
        outfile = outdir / Path(page.title().replace("/", "_"))
        with open(outfile, "w", encoding="utf-8") as outfile:
            print(text, file=outfile)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("download DIRECTORY")
        sys.exit(1)
    download(Path(sys.argv[1]))
